###############################################################################
# YAML description for local environment of the Service Orchestartion Kit.
# It's a minimal environment which you need to start a work with SOK on your
# local machine.
###############################################################################

product: !SOK:Include ../product.yml

environment:
  workspace: /tmp/sok

hosts:
  inventory: &inventory
    - 127.0.0.1
  registry: &registry
    - 127.0.0.1
  executor: &executor
    - 127.0.0.1
  console: &console
    - 127.0.0.1

roles:
  # Describe location of the inventory service
  inventory:
    services:
      - sok-inventory+file:///var/run/sok/inventory.soko
