###############################################################################
# YAML description for local environment of the Service Orchestartion Kit.
# It's a minimal environment which you need to start a work with SOK on your
# local machine.
###############################################################################

product: !SOK:Include ../product.yml

hosts:
  inventory: &inventory
    - 127.0.0.1
  registry: &registry
    - 127.0.0.1
  executor: &executor
    - 127.0.0.1
  console: &console
    - 127.0.0.1

environment: !SOK:Environment
  name: local
  workspace: ./local
  note: A single server environment, all services are located on the localhost
#  roles: *roles
#  product: *product
